shortener:
  base-url: ${SHORTENER_BASE_URL:http://localhost:8080}
  rate-limit:
    capacity: ${SHORTENER_RATE_LIMIT_CAPACITY:30}
    minutes: ${SHORTENER_RATE_LIMIT_MINUTES:1}
    burst:
      capacity: ${SHORTENER_RATE_LIMIT_BURST_CAPACITY:10}
      seconds: ${SHORTENER_RATE_LIMIT_BURST_SECONDS:5}
  cache-ttl-minutes: ${SHORTENER_CACHE_TTL_MINUTES:60}
  default-expiration: ${SHORTENER_DEFAULT_EXPIRATION:2880} # 48 hours
  maximum-expiration: ${SHORTENER_MAX_EXPIRATION:10080} # 1 week

spring:
  cassandra:
    keyspace-name: ${CASSANDRA_KEYSPACE:url_shortener}
    contact-points: ${CASSANDRA_CONTACT_POINTS:localhost}
    port: ${CASSANDRA_PORT:9042}
    schema-action: ${CASSANDRA_SCHEMA_ACTION:CREATE_IF_NOT_EXISTS}
    local-datacenter: ${CASSANDRA_DATACENTER:datacenter1}
    username: ${CASSANDRA_USERNAME:admin}
    password: ${CASSANDRA_PASSWORD:admin}
    connection:
      connect-timeout: ${CASSANDRA_CONNECT_TIMEOUT:30s}
      init-query-timeout: ${CASSANDRA_INIT_QUERY_TIMEOUT:30s}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true