spring:
  cassandra:
    keyspace-name: url_shortener
    contact-points: localhost
    port: 9042
    schema-action: CREATE_IF_NOT_EXISTS
    local-datacenter: datacenter1
    username: admin
    password: admin
    connection:
      connect-timeout: 30s
      init-query-timeout: 30s

server:
  port: 8080

app.base-url: http://localhost:8080
