shortener:
  base-url: http://test-url.com
  rate-limit:
    capacity: 30
    minutes: 1
    burst:
      capacity: 10
      seconds: 5
  cache-ttl-minutes: 60
  default-expiration: 2880
  maximum-expiration: 10080

spring:
  cassandra:
    keyspace-name: url_shortener
    contact-points: localhost
    port: 9042
    schema-action: CREATE_IF_NOT_EXISTS
    local-datacenter: datacenter1
    username: admin
    password: admin
    connection:
      connect-timeout: 30s
      init-query-timeout: 30s
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
